name: JS Actions
on:
  workflow_dispatch:
jobs:
  action:
    //runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: hello-action
      uses: ./.github/actions/javascript
