name: simple nodejs

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - uses: dreamcodez/dead-simple-nodejs@1
        with:
          NODE_VERSION: 16.1.0
          NODE_DISTRO: linux-x64 # optional
